### ISSUE TITLE
Some seqs are too long, please rebuild the program with make parameter MAX_SEQ=new-maximum-length

### ISSUE THREAD

**Issue by Vishu1511** [weizhongli/cdhit#100]
Hello there, I was working over my metagenomic data when I came across this issue of having too long sequences, while running `cd-hit-est` command as `./cd-hit-est -i ../../Desktop/analysis/megahit_result3/final.contigs.fa -o ../../Desktop/analysis/F_V_0_3_Rred.fa -S 1 -c 0.90 -n 5 -d 0 -M 5000 -T 8` I knwo this is not an issue of the command as I have already ran some data earlier.

But want to know how to set **MAX_SEQ=1000000**, i.e., how to recompile.?

Please help.!!!

Thanks, Vishal

**Comment by rotoscan** [comment]
Dear Vishal,

I had the same problem. You can recompile for longer sequences very easily by following the installation instructions and, once you compile with make, add the MAX_SEQ argument.

$ make MAX_SEQ=10000000
g++  -fopenmp -DWITH_ZLIB -O2 -DMAX_SEQ=10000000  cdhit-common.c++ -c
g++  -fopenmp -DWITH_ZLIB -O2 -DMAX_SEQ=10000000  cdhit-utility.c++ -c
g++  -fopenmp -DWITH_ZLIB -O2 -DMAX_SEQ=10000000  cdhit.c++ -c
g++  -fopenmp -DWITH_ZLIB -O2 -DMAX_SEQ=10000000  cdhit.o cdhit-common.o cdhit-utility.o -lz -o cd-hit
g++  -fopenmp -DWITH_ZLIB -O2 -DMAX_SEQ=10000000  cdhit-est.c++ -c
g++  -fopenmp -DWITH_ZLIB -O2 -DMAX_SEQ=10000000  cdhit-est.o cdhit-common.o cdhit-utility.o -lz -o cd-hit-est
g++  -fopenmp -DWITH_ZLIB -O2 -DMAX_SEQ=10000000  cdhit-2d.c++ -c
g++  -fopenmp -DWITH_ZLIB -O2 -DMAX_SEQ=10000000  cdhit-2d.o cdhit-common.o cdhit-utility.o -lz -o cd-hit-2d
g++  -fopenmp -DWITH_ZLIB -O2 -DMAX_SEQ=10000000  cdhit-est-2d.c++ -c
g++  -fopenmp -DWITH_ZLIB -O2 -DMAX_SEQ=10000000  cdhit-est-2d.o cdhit-common.o cdhit-utility.o -lz -o cd-hit-est-2d
g++  -fopenmp -DWITH_ZLIB -O2 -DMAX_SEQ=10000000  cdhit-div.c++ -c
g++  -fopenmp -DWITH_ZLIB -O2 -DMAX_SEQ=10000000  cdhit-div.o cdhit-common.o cdhit-utility.o -lz -o cd-hit-div
g++  -fopenmp -DWITH_ZLIB -O2 -DMAX_SEQ=10000000  cdhit-454.c++ -c
g++  -fopenmp -DWITH_ZLIB -O2 -DMAX_SEQ=10000000  cdhit-454.o cdhit-common.o cdhit-utility.o -lz -o cd-hit-454


It should work with no problem. =)

Best
Rodolfo

**Comment by liwang0307** [comment]
Hi @rotoscan @ @Vishu1511 , I had the same question. trying to fix it by deleting all .o files and running make MAX_SEQ=10000000. However, it didn't work for me. After 14 hours of running, the log file showed that it just sorted the sequences!  There are no error messages also. BTW, I have enough cups and memory, 32 cups and 240000m memory. Could you please let me know how you rebuild it in detail, please? Thank you so much!
