### ISSUE TITLE
Segmentation fault (core dumped) with cd-hit-est

### ISSUE THREAD

**Issue by dbolser-ebi** [weizhongli/cdhit#26]
Err:

    $ cd-hit-est -i my.fa -o my_cd_hit_est_100.fa -c 1 -M 0 -T 0
    ================================================================
    Program: CD-HIT, V4.6 (+OpenMP), Nov 09 2015, 16:19:49
    Command: 
         cd-hit-est
         -i my.fa -o
         my_cd_hit_est_100.fa -c
         1 -M 0 -T 0
    
    Started: Mon Nov  9 16:38:32 2015
    ================================================================
                            Output
    ----------------------------------------------------------------
    total number of CPUs in the system is 24
    Actual number of CPUs to be used: 24

    total seq: 735943
    
    Warning:
    Some seqs are too long, please rebuild the program with make parameter MAX_SEQ=new-maximum-length (e.g. make MAX_SEQ=10000000)
    Not fatal, but may affect results !!

    longest and shortest : 823974 and 500
    Total letters: 13427354022
    Sequences have been sorted

    Approximated minimal memory consumption:
    Sequence        : 13520M
    Buffer          : 24 X 196M = 4713M
    Table           : 2 X 28M = 57M
    Miscellaneous   : 13M
    Total           : 18303M
    
    Table limit with the given memory limit:
    Max number of representatives: 491581
    Max number of word counting entries: 233662760

    # comparing sequences from          0  to         43
    Segmentation fault (core dumped)

**Comment by dbolser-ebi** [comment]
Despite the message "Not fatal, but may affect results", I found re-compiling with increased MAX_SEQ solved the issue. Note that I had to recompile all tools, not just cdhit-est.c++. Just in case it matters, I tried recompiling cdhit-est.c++ alone with MAX_SEQ=10000000, which failed, then I tried recompiling all tools with MAX_SEQ=1000000.

**Comment by suyanan** [comment]
recompile with command:
$ make MAX_SEQ=10000000
