### ISSUE TITLE
Error: cd-hit-dup: bioSequence.cxx:46: void Bio::Sequence::Print(FILE*, int): Assertion `seq.Size() == qs.Size()' failed.

### ISSUE THREAD

**Issue by tv195** [weizhongli/cdhit#30]
Calling cd-hit-dup:

cd-hit-dup -i test.R1.fastq  -i2   test.R2.fastq  -o test.R1.CDhitDup.fastq   -o2 test.R2.CDhitDup.fastq   -u 50

I get the following error:

From input: test.R1.fastq
Total number of sequences: 4
Longest: 151
Shortest: 48

From input: test.R2.fastq
Total number of sequences: 4
Longest: 151
Shortest: 48
Start clustering duplicated sequences ...
primer = 0
Number of reads: 4
Number of clusters found: 4
Number of clusters with abundance above the cutoff (=1): 4
Number of clusters with abundance below the cutoff (=1): 0
Writing clusters to files ...
cd-hit-dup: bioSequence.cxx:46: void Bio::Sequence::Print(FILE*, int): Assertion `seq.Size() == qs.Size()' failed.
Aborted

version:
====== CD-HIT version 4.6 (built on Feb  8 2016) ======

files:
more  test.R1.fastq
@NS500333:45:HLTCLBGXX:1:11101:10485:1027 1:N:0:GGACTCCT+NGAGGATA
NCATANGGAGAGCATCCCAGTTCTTGAAGAATATTTAAAAATAGACCCTCGATCCACAGTGAGACTTCTCTCCAAAAAAGAGATGGAGTCGCAACACCCACTTTTCAAAAAAAATAAAAACTTTGGAGGTCTTCACAGTAC
+
#AAAA#FFFFAFFFFF7FFFFFFFFF<FFFFFFFFFFFFFFFFF.FAFFFF<FFFFFFFFFFFFFFFF7FFFFFFFAFFFFF.FFFFFFFAFA<FAF.<FFF<FFFA7AFFFFFFFFF7AFF<FFF<FFFFFFFFFFFF77
@NS500333:45:HLTCLBGXX:1:11101:14310:1028 1:N:0:GGACTCCT+NGAGGATA
NTGTCNTCGCAGCGCGGTCAGCTATATATGGAACTGAGATTTAACGGC
+
#AAAA#FFFFFFFFFFFFFAFFFFAFFFFFFFFFFFFFFAFFFAFFFF
@NS500333:45:HLTCLBGXX:1:11101:9055:1028 1:N:0:GGACTCCT+NGAGGATA
NATTTNTACCACTCGATTCTGCTAATTTATATGACAAGAATTCAAGAGTTATAATTCTATTTTCAAAAGCACTGAGATTTTCACGCATTATTTTTAAATTAAGATCTACCAGTTTTCTAGAGCTCTGTACTTCTTGTTGAATAACTAAATT
+
#AAAA#FFFFFF<FFFFFFFFFF<FFFFFFFFFAFFFFFFFFFFFFFFFFAFFFFFFF7FFFFFFFFFFFFFFF<FFFFFFFFFFFFFF.FFF<FA<FFFFFFFFFFFF7<FFFFFFF7FFFFFFFFFAFFFFFFFFFFAFFFFFF.<FF7
@NS500333:45:HLTCLBGXX:1:11101:6203:1028 1:N:0:GGACTCCT+NGAGGATA
NTTTANTATGAAGAGTAGAGACCTTAAATCCCTTATCCTTAAGGTATTCTTGCTCGTAGACTCTTACATCACTAACTTTATTTTGTATTTCTCTAATTGGTGTAATTGTTTTGTAATTTCCAAATGCTTGTATGGATAAATCAAATCTAA
+
#AA<A#FFFFFFFFFFFFAFAFFFFFFFFF7FFFFFFFFFAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF<<FFFFFFFFFFFFFFF7FFFFFFFFAFFFFF<FFFFAFFFFFF<<FFFFFFFFAFFF<FAFFFAFAFFFFFF

 more  test.R2.fastq
@NS500333:45:HLTCLBGXX:1:11101:10485:1027 2:N:0:GGACTCCT+NGAGGATA
GAACAGTGAAGACCTCCAAAGTATTTATTATTTTAGAAAAGTGCGTGTTGCGACTACATCTCTTTTTTGGAGAGAAGTCTCACTGTGGATCGAGGGTCTATTTTTAAATATTCTTCAAGAACTGGGATGCTCTCCTTATGT
+
))<.))F)<A<)FF)FF<.F.F)7F))FF)FFFA.<F.AFAF.)FF)A7.).AFFFAAFF...FF<F<FF.FF.<A<AFF77)<.F)).<.F7FA7FFFFFF<FFAFFFFFA<FFFAFFFFFFFF77FFFFF<FF<FFF<F
@NS500333:45:HLTCLBGXX:1:11101:14310:1028 2:N:0:GGACTCCT+NGAGGATA
GCCGTTAAATCTCAGTTCCATATATAGCTGACCGCGCTGCGAAGACAC
+
AAAAAFFFFFFFFFFFFFFFF<FFFFFFFF7FFFFFFFFFFFFFAFFF
@NS500333:45:HLTCLBGXX:1:11101:9055:1028 2:N:0:GGACTCCT+NGAGGATA
GAATTTAGTTATTCAACAAGAAGTACAGAGCTCTAGAAAACTGGTAGATCTTAATTTAAAAATAATGCGTGAAAATCTCAGTGCTTTTGAAAATAGAATTATAACTCTTGAATTCTTGTCATATAAATTAGCAGAATCGAGTGGTATAAAT
+
AAAAAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFAFFFFFFFF<FFFFFFFFFFFAFFFFFFFFFFFFFFFFFFFFF<FFFFFFFFFFA7FF<FFFFFFF.FFFFFFFAFFFFFFFFF<A<F7F.FFAAF7FFFFFA.<FAFF<F<FFA
@NS500333:45:HLTCLBGXX:1:11101:6203:1028 2:N:0:GGACTCCT+NGAGGATA
GTTAGATTTGATTTATCCATACAAGCATTTGGAAATTACAAAACAATTACACCAATTAGAGAAATACAAAATAAAGTTAGTGATGTAAGAGTCTACGAGCAAGAATACCTTAAGGATAAGGGATTTAAGGTCTCTACTCTTCATACTAAAT
+
AAA<AFFFFFFFFFAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF<<FFFF.FFFFFFFFFFFAFF<FFFFF.FFFAF<FAFFFFFFFFFA<FFAAFFAFFF.FF<<7FAF.AF<F7F<A<AF<FFFFFF7FFFAAFFAFF<7A7

Thanks,
Chris

**Comment by tv195** [comment]
Also I am using  
/blast/2.2.26 
Thx, Chris

**Comment by tv195** [comment]
Got the answer - see the note below from Weizhong Li: 


Try this command
>cd-hit-dup -i R1.fq -i2 R2.fq -u 48 -o dup
 
The minimal length of the input sequence is 48bp, with option –u 50, it requires to compare the first 50bp of each pair of reads.
 
cd-hit-dup doesn’t check this – this needs to be fixed in new cd-hit release, but will take some time.
 
For now, I would suggest to modify the parameter, or maybe filter out very short reads.
 
Thanks,
Weizhong

**Comment by weizhongli** [comment]
fixed in V4.6.6, Weizhong
