### ISSUE TITLE
Not enough memory when running cd-hit-est

### ISSUE THREAD

**Issue by GoogleCodeExporter** [weizhongli/cdhit#5]
```
What steps will reproduce the problem?
1. cd-hit-est -i all-contigs.fa -o all-contigs.fa.cdhit.out -M 2000 -c 0.99

What is the expected output? What do you see instead?

It turns out fine on at least half of our datasets, still there are a couple of 
input datasets will create this kind of errors.

What version of the product are you using? On what operating system?

CD-HIT 4.5.8 on Linux 2.6.18-274.12.1.el5 #1 SMP x86_64 GNU/Linux

Please provide any additional information below.

cd-hit-est -i all-contigs.fa -o all-contigs.fa.cdhit.out -M 2000 -c 0.99
================================================================
Program: CD-HIT, V4.5.8 (+OpenMP), Apr 06 2012, 00:18:06
Command: cd-hit-est -i all-contigs.fa -o
         all-contigs.fa.cdhit.out -M 2000 -c 0.99

Started: Tue Apr 24 12:08:35 2012
================================================================
                            Output
----------------------------------------------------------------
total seq: 57483
longest and shortest : 60345 and 200
Total letters: 52094767
Sequences have been sorted

Approximated minimal memory consumption:
Sequence        : 58M
Buffer          : 1 X 18446744071796M = 18446744071796M
Table           : 1 X 17M = 17M
Miscellaneous   : 4M
Total           : 18446744071877M


Fatal Error:
not enough memory, please set -M option greater than 18446744071927

Program halted !!

```

Original issue reported on code.google.com by `wche...@gmail.com` on 24 Apr 2012 at 4:21

**Comment by yyx8671** [comment]
Hi, 

I got a similar error
<pre>
================================================================
Program: CD-HIT, V4.7 (+OpenMP), May 27 2018, 19:32:02
Command: cd-hit-est -i my.fasta -o test -T 8 -M 800
Started: Sun May 27 19:37:14 2018
================================================================
                            Output                              
----------------------------------------------------------------
total seq: 38196
longest and shortest : 33894285 and 1001
Total letters: 1296355284
Sequences have been sorted

Approximated minimal memory consumption:
Sequence        : 1301M
Buffer          : 8 X 18446744072901M = 18446744067242M
Table           : 2 X 17M = 34M
Miscellaneous   : 4M
Total           : 18446744068582M

Fatal Error:
not enough memory, please set -M option greater than 18446744068682

Program halted !!
</pre>

the program was compiled using ``make MAX_SEQ=35000000``,  do you have any idea to fix this? 

Many thanks,
Andy
