### ISSUE TITLE
is input required to be sorted?

### ISSUE THREAD

**Issue by hildebra** [weizhongli/cdhit#66]
Hey, since this has been an ever recurring question (maybe this could also be clarified in the cd-hit-est help message): Does the input of the actual cd-hit-est version need to be length sorted? 
thanks,
Falk

**Comment by hildebra** [comment]
Just to add to this discussion, I tested this and my impression is that the user needs to sort the input fasta file by length (and it is important to do that).

**Comment by mr-eyes** [comment]
@hildebra How does that affects the cd-hit run?
Can you share more information?

**Comment by weizhongli** [comment]
A user don't need to sort the input sequence, cd-hit with sort them.
