### ISSUE TITLE
clstr_rev.pl not merging cluster files

### ISSUE THREAD

**Issue by driscollmml** [weizhongli/cdhit#71]
I am trying to build hierarchical clusters at 25% ID:
cd-hit -i MYSEQS.faa -o bf50 -c 0.5 -n 3 -g 1
psi-cd-hit.pl -i bf50 -o bf25 -c 0.25 -ce 1e-6 -aS 0.8 -G 0 -g 1
clstr_rev.pl bf50.clstr bf25.clstr > bf_final.clstr

no errors are thrown, but the files bf_final.clstr and bf25.clstr are identical. it seems that clstr_rev.pl isn't adding parent clusters.

**Comment by driscollmml** [comment]
turns out this issue arises when sequence ids are too long (not sure what is the length cutoff exactly). in this case the ids are truncated in the clstr file by CD-HIT, but apparently they are not truncated by psi-cd-hit.pl.

**Comment by weizhongli** [comment]
Yes, you are right. 

Plan to set 0 as default for -d option.
