### ISSUE TITLE
Sorting by length utility inside CD-HIT?

### ISSUE THREAD

**Issue by anandksrao** [weizhongli/cdhit#72]
Is there a CD-HIT function to sort input sequences by length? 

A while back, I remember sorting my input by length, before the CD-HIT step _per se_. 

But now, I can't seem to remember if it was a Perl script or some other executable inside CD-HIT or from elsewhere. Can someone help? Thanks! HNY 2019!

**Comment by weizhongli** [comment]
cd-hit sorts input internally, there is no perl script in cd-hit package for sorting.

But I do have a simple script at another package can sort fasta file by length: 
https://github.com/weizhongli/ngomicswf/blob/master/NGS-tools/fasta_sort_by_len.pl

It reads all sequences into RAM, so be careful with very large file.
